sudo: required
dist: trusty
language: python
branches:
  only:
    - master

before_install:
  - export ANDROID_HOME=$HOME/Android/Sdk/
  - export NDK=$HOME/Android/Sdk/ndk-bundle

  # Install android tools
  - mkdir -p $ANDROID_HOME
  - cd $ANDROID_HOME
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      wget https://dl.google.com/android/repository/sdk-tools-linux-3859397.zip -O tools.zip;
     else
      wget https://dl.google.com/android/repository/sdk-tools-darwin-3859397.zip -O tools.zip;
    fi
  - unzip -oq tools.zip
  - rm *.zip

  # Install sdk, ndk, and build tools
  - echo yes | tools/bin/sdkmanager --update > output.log
  - echo yes | tools/bin/sdkmanager "platforms;android-27" > output.log
  - echo yes | tools/bin/sdkmanager "build-tools;27.0.3" > output.log
  - echo yes | tools/bin/sdkmanager "extras;google;m2repository" > output.log
  - echo yes | tools/bin/sdkmanager "extras;android;m2repository" > output.log
  - echo yes | tools/bin/sdkmanager "system-images;android-25;google_apis;armeabi-v7a" > output.log
  - echo yes | tools/bin/sdkmanager "ndk-bundle" > output.log
  - echo yes | tools/bin/sdkmanager --licenses > output.log

  # Start the emulator!
  - tools/bin/avdmanager list
  - ln -s tools/emulator64-x86 tools/emulator-x86
  - echo no | tools/bin/avdmanager create avd --force --name test --package 'system-images;android-25;google_apis;armeabi-v7a'
  - tools/emulator -avd test -no-audio -no-window &
  #- platform-tools/adb wait-for-device
  - cd $TRAVIS_BUILD_DIR

  # Install miniconda
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
       wget http://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
     else
       wget https://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a


install:

  # Install enaml-native-cli (check that build script is not broken)
  - cd $TRAVIS_BUILD_DIR
  - python setup.py develop
  - cd ~


script:

  # Create and run an app
  - cd $TRAVIS_BUILD_DIR

  # Create HelloWorld app and run it
  - mkdir tmp
  - cd tmp
  - enaml-native create app --no-input
  - cd HelloWorld
  - source activate ./venv
  - enaml-native run-android
