sudo: required
dist: trusty
language: android
jdk: oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-26.0.2

    # The SDK version used to compile your project
    - android-27

    #: Add android image
    - android-22 # Android platform used by your alternative emulator
    - sys-img-armeabi-v7a-android-22
    - extra-google-m2repository
    - extra-android-m2repository

branches:
  only:
    - master

before_install:
  # Install miniconda
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
       wget http://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
     else
       wget https://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

install:

  # Install enaml-native-cli (check that build script is not broken)
  - cd $TRAVIS_BUILD_DIR
  - python setup.py develop
  - cd ~


script:

  # Create and run an app
  - cd $TRAVIS_BUILD_DIR

  # Create HelloWorld app and run it
  - mkdir tmp
  - cd tmp
  - enaml-native create app --noinput
  - cd HelloWorld
  - source activate ./venv
  - enaml-native run-android
