package:
  name: enaml-native-cli
  version: 2.2.4

requirements:
  build:
    - python
  run:
    - pip
    - requests
    - atom
    - tornado
    # On linux you must apt install build-essential autopoint texinfo
    - libtool # [not win]
    - autoconf # [not win]
    - automake # [not win]

    # These don't have windows packagesy
    - cookiecutter # [not win]
    - sh # [not win]
    - ruamel.yaml # [not win]
    - watchdog # [not win]


build:
  number: 2
  noarch: python
  include_recipe: False
  script:
    - cd $RECIPE_DIR
    - python setup.py install --single-version-externally-managed --record=record.txt --no-compile
  entry_points:
    - enaml-native = enamlnativecli.main:main
about:
  home: http://github.com/codelv/enaml-native-cli
  summary: "CLI for building android and iOS apps using enaml-native"
  license: GPLv3